# Generated by Django 3.0.7 on 2020-06-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decyzja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('tresc', models.TextField(help_text='Wpisz treść przepisu w takim brzmieniu w jakim ma obowiązywać.', max_length=500, null=True, verbose_name='Treść')),
                ('kara', models.TextField(help_text='Jaka kara ma obowiązywać za nieprzestrzeganie tego przpisu. Może to być np. Banicja na 3 miesiące, Banicja na zawsze, itd.', max_length=500, null=True, verbose_name='Kara')),
                ('uzasadnienie', models.TextField(help_text='Co jest celem tego przepisu? Dlaczego powstał? Co mamy dzięki niemu osiągnąć? Jakie wydarzenie spowodowało jego powstanie?', max_length=1500, null=True, verbose_name='Uzasadnienie')),
                ('znosi', models.CharField(blank=True, help_text='Jeśli proponowany przepis znosi inne przepisy to wpisz ich numery tutaj. Kolejne numery przepisów rozdziel przecinkami.', max_length=500, null=True, verbose_name='Znosi przepisy')),
                ('ile_osob_podpisalo', models.SmallIntegerField(default=0, editable=False)),
                ('data_powstania', models.DateField(auto_now_add=True, null=True)),
                ('data_zebrania_podpisow', models.DateField(editable=False, null=True)),
                ('data_referendum_start', models.DateField(editable=False, null=True)),
                ('data_referendum_stop', models.DateField(editable=False, null=True)),
                ('data_zatwierdzenia', models.DateField(editable=False, null=True)),
                ('data_obowiazuje_od', models.DateField(editable=False, null=True)),
                ('za', models.SmallIntegerField(default=0, editable=False)),
                ('przeciw', models.SmallIntegerField(default=0, editable=False)),
                ('status', models.SmallIntegerField(default=1, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Decyzje',
            },
        ),
        migrations.CreateModel(
            name='ZebranePodpisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpis_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.Decyzja')),
            ],
            options={
                'unique_together': {('projekt', 'podpis_uzytkownika')},
            },
        ),
        migrations.CreateModel(
            name='KtoJuzGlosowal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktory_uzytkownik_juz_zaglosowal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.Decyzja')),
            ],
            options={
                'unique_together': {('projekt', 'ktory_uzytkownik_juz_zaglosowal')},
            },
        ),
    ]
