# Generated by Django 2.0.12 on 2019-03-24 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decyzja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('tresc', models.TextField(max_length=500, null=True, verbose_name='Treść')),
                ('kara', models.TextField(max_length=500, null=True, verbose_name='Kara')),
                ('ile_osob_podpisalo', models.SmallIntegerField(default=0, editable=False)),
                ('data_powstania', models.DateField(editable=False, null=True)),
                ('data_zebrania_podpisow', models.DateField(editable=False, null=True)),
                ('data_referendum', models.DateField(editable=False, null=True)),
                ('data_obowiazuje_od', models.DateField(editable=False, null=True)),
                ('za', models.SmallIntegerField(default=0, editable=False)),
                ('przeciw', models.SmallIntegerField(default=0, editable=False)),
                ('status', models.SmallIntegerField(default=1, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Decyzje',
            },
        ),
        migrations.CreateModel(
            name='KtoJuzGlosowal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktory_uzytkownik_juz_zaglosowal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.Decyzja')),
            ],
        ),
        migrations.CreateModel(
            name='ZebranePodpisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpis_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.Decyzja')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zebranepodpisy',
            unique_together={('projekt', 'podpis_uzytkownika')},
        ),
        migrations.AlterUniqueTogether(
            name='ktojuzglosowal',
            unique_together={('projekt', 'ktory_uzytkownik_juz_zaglosowal')},
        ),
    ]
