# Generated by Django 2.0.12 on 2019-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decyzja',
            old_name='data_referendum',
            new_name='data_referendum_start',
        ),
        migrations.AddField(
            model_name='decyzja',
            name='data_referendum_stop',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='decyzja',
            name='data_zatwierdzenia',
            field=models.DateField(editable=False, null=True),
        ),
    ]
