# Generated by Django 2.0.12 on 2019-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(max_length=1500, null=True, verbose_name='Uzasadnienie'),
        ),
    ]
