# Generated by Django 2.0.12 on 2019-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0002_decyzja_uzasadnienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='data_powstania',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
