# Generated by Django 3.1 on 2020-11-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0003_auto_20201122_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decyzja',
            options={},
        ),
    ]
