# Generated by Django 2.2 on 2019-06-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0003_auto_20190520_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='kara',
            field=models.TextField(help_text='asdasd', max_length=500, null=True, verbose_name='Kara'),
        ),
    ]
