# Generated by Django 3.1 on 2020-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0004_auto_20201122_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='kara',
            field=models.TextField(help_text='What is the penalty for non-compliance with this rule. This can be, for example: "Banishment for 3 months", "Banishment forever", etc.', max_length=500, null=True, verbose_name='Penalty'),
        ),
    ]
