# Generated by Django 2.2 on 2019-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0004_auto_20190602_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='kara',
            field=models.TextField(help_text='Jaka kara ma obowiązywać za nie                                nie przestrzeganie tego przpisu. Może to być                                np. Banicja na 3 miesiące, Banicja na zawsze,                                itd.', max_length=500, null=True, verbose_name='Kara'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='tresc',
            field=models.TextField(help_text='Wpisz ostateczną treść przepisu                                 w takim brzmieniu w jakim ma obowiązywać.', max_length=500, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='Co jest celem tego przepisu?                                        Dlaczego powstał? Co mamy dzięki niemu                                        osiągnąć? Jakie wydarzenie spowodowało                                        jego powstanie?', max_length=1500, null=True, verbose_name='Uzasadnienie'),
        ),
    ]
