# Generated by Django 2.2 on 2019-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0005_auto_20190602_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='Co jest celem tego przepisu?                                        Dlaczego powstał? Co mamy dzięki niemu                                        osiągnąć? Jakie wydarzenie spowodowało                                        jego \n powstanie?', max_length=1500, null=True, verbose_name='Uzasadnienie'),
        ),
    ]
