# Generated by Django 3.1 on 2021-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0006_auto_20210117_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='args_against',
            field=models.TextField(help_text='What can go wrong if we will have it? What are the risks?', max_length=1500, null=True, verbose_name='Arguments against'),
        ),
        migrations.AddField(
            model_name='decyzja',
            name='args_for',
            field=models.TextField(help_text='Why should have this law? What will it give us?', max_length=1500, null=True, verbose_name='Arguments for'),
        ),
    ]
