# Generated by Django 2.2 on 2019-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0006_auto_20190602_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='znosi',
            field=models.CharField(help_text='Jeśli proponowany przepis znosi inne                                przepisy to wpisz ich numery tutaj. Kolejne                                numery przepisów rozdziel przecinkami.', max_length=500, null=True, verbose_name='Znosi przepisy'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='Co jest celem tego przepisu?                                        Dlaczego powstał? Co mamy dzięki niemu                                        osiągnąć? Jakie wydarzenie spowodowało                                        jego powstanie?', max_length=1500, null=True, verbose_name='Uzasadnienie'),
        ),
    ]
