# Generated by Django 3.1 on 2021-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0007_auto_20210207_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='args_against',
            field=models.TextField(help_text='Enter the potential threat associated with the proposal.', max_length=1500, null=True, verbose_name='Negative Aspects of the Idea'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='args_for',
            field=models.TextField(help_text='Enter the benefits for the group, environment, economy, etc. resulting from the introduction of the idea.', max_length=1500, null=True, verbose_name='Positive Aspects of the Idea'),
        ),
    ]
