# Generated by Django 2.2 on 2019-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0007_auto_20190602_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='znosi',
            field=models.CharField(blank=True, help_text='Jeśli proponowany przepis znosi inne                                przepisy to wpisz ich numery tutaj. Kolejne                                numery przepisów rozdziel przecinkami.', max_length=500, null=True, verbose_name='Znosi przepisy'),
        ),
    ]
