# Generated by Django 2.2 on 2019-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0008_auto_20190602_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='tresc',
            field=models.TextField(help_text='Wpisz treść przepisu w takim brzmieniu                                 w jakim ma obowiązywać.', max_length=500, null=True, verbose_name='Treść'),
        ),
    ]
