# Generated by Django 3.1.12 on 2021-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0008_auto_20210227_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='What events inspired this bill? What are we going to achieve with it?', max_length=1500, null=True, verbose_name='Reasoning'),
        ),
    ]
