# Generated by Django 3.1.12 on 2021-10-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0009_auto_20210818_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, null=True)),
                ('vote', models.BooleanField(editable=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.decyzja')),
            ],
        ),
    ]
