# Generated by Django 3.1.12 on 2021-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0016_auto_20211013_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='znosi',
            field=models.CharField(blank=True, help_text='If the proposed law supersedes other recipes, enter their comma separated numbers here.', max_length=50, null=True, verbose_name='Abolishes the rules'),
        ),
    ]
