# Generated by Django 3.1.12 on 2021-10-13 14:59

from django.db import migrations, models
import glosowania.models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0018_auto_20211013_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='znosi',
            field=models.CharField(blank=True, help_text='If the proposed law supersedes other recipes, enter their numbers here.', max_length=50, null=True, validators=[glosowania.models.does_it_exist], verbose_name='Abolishes the rules'),
        ),
    ]
