# Generated by Django 6.0.4 on 2026-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0019_alter_decyzja_kara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='Why do we need this law? What events or thoughts inspired this bill? What are the expected results?', max_length=4000, null=True, verbose_name='Reasoning'),
        ),
    ]
