# Generated by Django 6.0.4 on 2026-06-29 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0020_alter_decyzja_uzasadnienie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecyzjaWersja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('version_number', models.PositiveSmallIntegerField(verbose_name='Version')),
                ('title', models.TextField(max_length=200, null=True)),
                ('tresc', models.TextField(max_length=3000, null=True)),
                ('kara', models.TextField(blank=True, max_length=500, null=True)),
                ('uzasadnienie', models.TextField(max_length=4000, null=True)),
                ('znosi', models.CharField(blank=True, max_length=50, null=True)),
                ('decyzja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wersje', to='glosowania.decyzja', verbose_name='Decision')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Decision version',
                'verbose_name_plural': 'Decision versions',
                'ordering': ['version_number'],
            },
        ),
    ]
