# Generated by Django 3.1.12 on 2021-10-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0022_auto_20211013_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decyzja',
            old_name='autor',
            new_name='author',
        ),
    ]
