# Generated by Django 6.0.4 on 2026-07-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_add_guest_inbox_fields'),
        ('glosowania', '0023_decyzja_proposed_brand_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='chat.room', verbose_name='Chat room'),
        ),
    ]
