# Generated by Django 6.0.4 on 2026-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0024_alter_decyzja_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Proposition'), (2, 'Discussion'), (3, 'Referendum'), (4, 'Rejected'), (5, 'Approved')], default=1, editable=False),
        ),
    ]
