# Generated by Django 6.0.4 on 2026-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0025_alter_decyzja_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='referendum_restart_count',
            field=models.SmallIntegerField(default=0, editable=False, help_text='How many times voting had to restart from scratch because the vote buffer was lost (e.g. Redis restart) before it closed.', verbose_name='Referendum restart count'),
        ),
    ]
