# Generated by Django 6.0.8 on 2026-09-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('glosowania', '0027_backfill_room_source')]

    operations = [
        migrations.CreateModel(
            name='ReferendumEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parameters', 'System parameters'), ('brand_mark', 'Brand mark'), ('buffer_ack', 'Vote buffer acknowledgement')], max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referendum_effects', to='glosowania.decyzja')),
            ],
            options={'constraints': [models.UniqueConstraint(fields=('decision', 'kind'), name='unique_referendum_effect_kind')]},
        )
    ]
