# Generated by Django 6.0.4 on 2026-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0030_transaction_asset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
