# Generated by Django 6.0.8 on 2026-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('bookkeeping', '0032_alter_transaction_author')]

    operations = [migrations.AddField(model_name='transaction', name='updated_at', field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated'))]
