services:
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data/db:/app/db
      - ./data/media:/app/media

  chat_notifications_worker:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: ["python", "manage.py", "run_chat_notifications_worker"]
    volumes:
      - ./data/db:/app/db
      - ./data/media:/app/media
