[project]
name = "wikikracja"
version = "0.0.0"
requires-python = ">= 3.14"

[tool.ruff]
line-length = 210
target-version = "py313"  # keep py313 until ruff stops stripping except parentheses for py314
# preview = true
show-fixes = true
# unsafe-fixes = true
exclude = [".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".mypy_cache", ".nox", ".pants.d", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build", "buck-out", "dist", "node_modules", "venv", "migrations"]

[tool.ruff.analyze]
# detect-string-imports = true
# preview = true

[tool.ruff.format]
docstring-code-format = true
# indent-style = "space" # set to tab after first format all files ??
line-ending = "lf"
# preview = true
quote-style = "preserve"
# set to double ??  "preserve" now? single
skip-magic-trailing-comma = true

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = ["B"]
# check disabled after 1st format
ignore = ["E501","T201"]
select = ["E4", "E7", "E9", "E", "F", "I", "B", "W", "T"]
#, "Q"]
# preview = true
task-tags = ["TODO", "FIXME", "XXX", "HACK"]
typing-extensions = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.ruff.lint.isort]
# no-sections = true
split-on-trailing-comma=false

[tool.ruff.lint.flake8-type-checking]
#strict = true # ??? usable


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "zzz.test_settings"
python_files = "test_*.py tests.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests", "board", "bookkeeping", "chat", "events", "glosowania", "obywatele", "tasks", "home", "site_settings"]
