# Generated by Django 6.0.8 on 2026-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbookmark',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Activity'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity'), ('survey', 'Survey'), ('decision_argument', 'Voting argument')], max_length=20),
        ),
    ]
