# Generated by Django 3.1 on 2020-09-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200906_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
