# Generated by Django 3.1 on 2021-01-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='staff_only',
        ),
    ]
