# Generated by Django 3.1 on 2021-01-02 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_room_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allowed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
