# Generated by Django 3.1 on 2021-01-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
