# Generated by Django 3.1 on 2021-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_room_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
