# Generated by Django 6.0.4 on 2026-04-24 16:23

from django.db import migrations, models


def populate_reactions(apps, schema_editor):
    """
    Populate the reactions JSONField from old MessageVote and MessageReaction tables.
    Structure: {upvotes: [user_ids], downvotes: [user_ids], bulb: [user_ids], question: [user_ids]}
    """
    Message = apps.get_model('chat', 'Message')
    # Use historical models (they still exist in this migration state)
    try:
        MessageVote = apps.get_model('chat', 'MessageVote')
        has_votes = True
    except (LookupError):
        has_votes = False
    
    try:
        MessageReaction = apps.get_model('chat', 'MessageReaction')
        has_reactions = True
    except (LookupError):
        has_reactions = False
    
    # Get all message IDs to avoid model instantiation issues
    message_ids = list(Message.objects.values_list('id', flat=True))
    
    for message_id in message_ids:
        reactions_dict = {}
        
        # Populate from MessageVote (upvotes/downvotes)
        if has_votes:
            upvotes = []
            downvotes = []
            votes = MessageVote.objects.filter(message_id=message_id)
            for vote in votes:
                if vote.vote == 'upvote':
                    upvotes.append(vote.user_id)
                else:
                    downvotes.append(vote.user_id)
            if upvotes:
                reactions_dict['upvotes'] = upvotes
            if downvotes:
                reactions_dict['downvotes'] = downvotes
        
        # Populate from MessageReaction (bulb/question)
        if has_reactions:
            bulb = []
            question = []
            msg_reactions = MessageReaction.objects.filter(message_id=message_id)
            for reaction in msg_reactions:
                if reaction.reaction == 'bulb':
                    bulb.append(reaction.user_id)
                elif reaction.reaction == 'question':
                    question.append(reaction.user_id)
            if bulb:
                reactions_dict['bulb'] = bulb
            if question:
                reactions_dict['question'] = question
        
        # Only update if there's data
        if reactions_dict:
            # Use update to avoid model instantiation issues
            Message.objects.filter(id=message_id).update(reactions=reactions_dict)


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: clear the reactions JSONField.
    """
    Message = apps.get_model('chat', 'Message')
    Message.objects.update(reactions={})


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_reactions_jsonfield_to_message'),
    ]

    operations = [
        migrations.RunPython(populate_reactions, reverse_populate),
    ]