# Generated by Django 3.1.12 on 2021-10-13 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0015_auto_20211010_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
