# Generated by Django 3.1.12 on 2021-10-13 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_room_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
