# Generated by Django 3.1.12 on 2021-10-16 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0020_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='muted_by',
            field=models.ManyToManyField(related_name='muted_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
