# Generated by Django 6.0.4 on 2026-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_backfill_room_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='is_inbox',
            field=models.BooleanField(default=False),
        ),
    ]
