# Generated by Django 6.0.4 on 2026-09-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_add_guest_inbox_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='source_app',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
