# Generated by Django 3.1.12 on 2021-10-21 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0021_room_muted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allowed',
            field=models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
