# Generated by Django 6.0.8 on 2026-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_room_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
