# Generated by Django 6.0.8 on 2026-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_room_system_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='federation_message_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='federated_instance_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='federated_instance_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
