# Generated by Django 6.0.8 on 2026-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_message_federation_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='federation_communication_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='federation_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='federation_last_communication_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='federation_peer_configured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
