# Generated by Django 6.0.8 on 2026-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_room_federation_communication_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='federated_read_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='federation_source_message_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='federation_source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
