# Generated by Django 6.0.8 on 2026-09-27 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_message_federated_read_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='manually_muted_by',
            field=models.ManyToManyField(related_name='manually_muted_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
