# Generated by Django 6.0.8 on 2026-09-27 16:23

from django.db import migrations


def copy_existing_manual_mutes(apps, schema_editor):
    Room = apps.get_model('chat', 'Room')
    old_through = Room._meta.get_field('muted_by').remote_field.through
    new_through = Room._meta.get_field('manually_muted_by').remote_field.through
    new_through.objects.bulk_create(
        [new_through(room_id=row['room_id'], user_id=row['user_id']) for row in old_through.objects.values('room_id', 'user_id')],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_room_manually_muted_by'),
    ]

    operations = [
        migrations.RunPython(copy_existing_manual_mutes, migrations.RunPython.noop),
    ]
