# Generated by Django 6.0.8 on 2026-10-08 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_copy_existing_manual_room_mutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_object_id'), name='chat_room_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('source_object_id__isnull', True), models.Q(('source_app', ''), _negated=True), _connector='OR'), name='chat_room_source_app_ck'),
        ),
    ]
