# Generated by Django 6.0.4 on 2026-08-07 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('end_date', models.DateTimeField(help_text='After this moment the survey will be closed.', verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Option text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ankiety.survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Survey option',
                'verbose_name_plural': 'Survey options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ankiety.surveyoption', verbose_name='Chosen option')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ankiety.survey', verbose_name='Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Survey vote',
                'verbose_name_plural': 'Survey votes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'user'), name='ankiety_surveyvote_unique_vote')],
            },
        ),
    ]
