# Generated by Django 6.0.4 on 2026-08-09 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyvote',
            name='ankiety_surveyvote_unique_vote',
        ),
        migrations.AddField(
            model_name='survey',
            name='allow_multiple_choice',
            field=models.BooleanField(default=False, help_text='If enabled, users can select more than one option when voting.', verbose_name='Allow multiple choice'),
        ),
        migrations.AddConstraint(
            model_name='surveyvote',
            constraint=models.UniqueConstraint(fields=('survey', 'user', 'option'), name='ankiety_surveyvote_unique_vote'),
        ),
    ]
