# Generated by Django 6.0.4 on 2026-08-09 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0002_remove_surveyvote_ankiety_surveyvote_unique_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(3000)], verbose_name='Description'),
        ),
    ]
