# Generated by Django 5.2.16 on 2026-09-11 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0003_alter_survey_description'),
        ('chat', '0022_room_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_custom_options',
            field=models.BooleanField(default=False, help_text='If enabled, participants can add their own options while the survey is active.', verbose_name='Allow participants to add options'),
        ),
        migrations.AddField(
            model_name='survey',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='chat.room', verbose_name='Chat room'),
        ),
        migrations.AddField(
            model_name='surveyoption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_options_created', to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
    ]
