# Generated by Django 3.1.12 on 2021-08-18 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified')),
                ('published', models.BooleanField(default=True)),
                ('body', tinymce.models.HTMLField(verbose_name='Body')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-modified'],
            },
        ),
    ]
