# Generated by Django 3.1.12 on 2021-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=255, verbose_name='Title'), verbose_name='Image'),
        ),
    ]
