# Generated by Django 3.1.12 on 2021-08-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
