# Generated by Django 3.1.12 on 2021-08-15 22:57

import datetime
from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d', verbose_name='Image')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified')),
                ('published', models.BooleanField(default=False)),
                ('body', tinymce.models.HTMLField(verbose_name='Body')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'ordering': ['-modified'],
            },
        ),
    ]
