# Generated by Django 6.0.4 on 2026-07-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_feeditem_content_type_and_more'),
        ('site_settings', '0003_quicklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinkReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('quick_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='site_settings.quicklink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick link read status',
                'verbose_name_plural': 'Quick link read statuses',
                'unique_together': {('user', 'quick_link')},
            },
        ),
    ]
