# Generated by Django 6.0.4 on 2026-07-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_quicklinkreadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingProgress',
        ),
    ]
