# Generated by Django 6.0.4 on 2026-07-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_onboardingprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickLinkReadStatus',
        ),
    ]
