# Generated by Django 6.0.4 on 2026-08-05 11:57

from django.db import migrations


def _migrate_chat_read_status_to_seen_by(apps, schema_editor):
    """Move chat read-tracking from ReadStatus to Room.seen_by.

    The feed now uses Room.seen_by as the single source of truth for chat
    rooms, matching the chat module. Existing ReadStatus rows for
    content_type='message' are migrated to the M2M relation and then removed
    to avoid stale data and duplicate counting.
    """
    ReadStatus = apps.get_model('home', 'ReadStatus')
    Room = apps.get_model('chat', 'Room')
    RoomSeenBy = Room.seen_by.through

    valid_room_ids = set(Room.objects.values_list('id', flat=True))
    message_statuses = list(
        ReadStatus.objects.filter(content_type='message', object_id__in=valid_room_ids)
    )
    if not message_statuses:
        return

    room_ids = {rs.object_id for rs in message_statuses}
    user_ids = {rs.user_id for rs in message_statuses}

    existing = set(
        RoomSeenBy.objects.filter(
            room_id__in=room_ids,
            user_id__in=user_ids,
        ).values_list('room_id', 'user_id')
    )

    to_create = [
        RoomSeenBy(room_id=rs.object_id, user_id=rs.user_id)
        for rs in message_statuses
        if (rs.object_id, rs.user_id) not in existing
    ]

    if to_create:
        RoomSeenBy.objects.bulk_create(to_create, ignore_conflicts=True)

    ReadStatus.objects.filter(content_type='message').delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_quicklinkreadstatus'),
    ]

    operations = [
        migrations.RunPython(_migrate_chat_read_status_to_seen_by, _noop),
    ]
