# Generated by Django 6.0.4 on 2026-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20260805_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity'), ('survey', 'Survey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity'), ('survey', 'Survey')], max_length=20),
        ),
    ]
