# Generated by Django 6.0.4 on 2026-09-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_feeditem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Activity'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity'), ('survey', 'Survey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Activity'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity'), ('survey', 'Survey')], max_length=20),
        ),
    ]
