# Generated by Django 6.0.4 on 2026-09-04 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_backfill_room_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_helpers',
            field=models.ManyToManyField(blank=True, related_name='tasks_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved helpers'),
        ),
        migrations.AddField(
            model_name='task',
            name='team_mode',
            field=models.BooleanField(default=False, verbose_name='Team mode'),
        ),
    ]
