# Generated by Django 6.0.8 on 2026-10-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_room_chat_room_source_uniq_and_more'),
        ('tasks', '0012_add_task_team_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='chat.room', verbose_name='Chat room'),
        ),
    ]
