# Generated by Django 3.1.12 on 2021-08-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customize',
            name='mod_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customize',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
