# Generated by Django 3.1.12 on 2021-08-13 16:17

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_auto_20210813_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=models.TextField(),
        ),
    ]
