# Generated by Django 3.1.12 on 2021-08-13 16:19

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_auto_20210813_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
