# Generated by Django 3.1.12 on 2021-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_auto_20210813_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=models.TextField(),
        ),
    ]
