# Generated by Django 3.1.12 on 2021-08-13 17:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_auto_20210813_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
