# Generated by Django 3.1.12 on 2021-08-13 18:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0008_auto_20210813_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='customize',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
