# Generated by Django 6.0.4 on 2026-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_brand_mark_sitesettings_brand_mark_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Icon (FontAwesome class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Quick link',
                'verbose_name_plural': 'Quick links',
                'ordering': ['order'],
            },
        ),
    ]
