# Generated by Django 6.0.4 on 2026-07-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_add_sample_quick_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='onboarding_category',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='onboarding_posts',
        ),
    ]
