# Generated by Django 6.0.4 on 2026-07-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_remove_sitesettings_branding_text_and_brand_mark_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteparameters',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='siteparameters',
            name='site_name_max_12_chars',
        ),
    ]
