# Generated by Django 6.0.4 on 2026-08-13 17:42

import site_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_remove_siteparameters_site_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_mark',
            field=models.ImageField(blank=True, help_text='Graphic mark (PNG/JPEG/WebP/GIF, max 5 MB, source 64-4096 px). Resized to 1024×1024 px PNG with letterbox and converted to favicon/PWA icons on save.', null=True, upload_to='site_branding/', validators=[site_settings.validators.validate_branding_image_size, site_settings.validators.validate_brand_mark_dimensions, site_settings.validators.validate_brand_mark_format], verbose_name='Brand mark'),
        ),
    ]
