# Generated by Django 6.0.4 on 2026-09-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_sitesettings_brand_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicklink',
            name='icon',
        ),
    ]
