# Generated by Django 6.0.8 on 2026-09-13 00:01

from django.db import migrations, models

import site_settings.validators


def copy_brand_mark(apps, schema_editor):
    SiteSettings = apps.get_model('site_settings', 'SiteSettings')
    SiteParameters = apps.get_model('site_settings', 'SiteParameters')
    source = SiteSettings.objects.filter(pk=1).first()
    if source is None or not source.brand_mark:
        return

    target, _created = SiteParameters.objects.get_or_create(pk=1)
    target.brand_mark = source.brand_mark
    target.save(update_fields=['brand_mark'])


def restore_brand_mark(apps, schema_editor):
    SiteSettings = apps.get_model('site_settings', 'SiteSettings')
    SiteParameters = apps.get_model('site_settings', 'SiteParameters')
    source = SiteParameters.objects.filter(pk=1).first()
    if source is None or not source.brand_mark:
        return

    target, _created = SiteSettings.objects.get_or_create(pk=1)
    target.brand_mark = source.brand_mark
    target.save(update_fields=['brand_mark'])


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_remove_quicklink_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteparameters',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AddField(
            model_name='siteparameters',
            name='brand_mark',
            field=models.ImageField(blank=True, help_text='Graphic mark (PNG/JPEG/WebP/GIF, max 5 MB, source 64-4096 px). Resized to 1024×1024 px PNG with letterbox and converted to favicon/PWA icons on save.', null=True, upload_to='site_branding/', validators=[site_settings.validators.validate_branding_image_size, site_settings.validators.validate_brand_mark_dimensions, site_settings.validators.validate_brand_mark_format], verbose_name='Brand mark'),
        ),
        migrations.RunPython(copy_brand_mark, restore_brand_mark),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
