# Generated by Django 2.0.12 on 2019-03-24 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import obywatele.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', obywatele.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AkceptacjaOsoby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputacja', models.SmallIntegerField(default=0, null=True)),
                ('polecajacy', models.CharField(editable=False, max_length=64, null=True)),
                ('data_przyjecia', models.DateField(editable=False, null=True)),
                ('uid', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='akceptacjaosoby',
            name='kandydat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydat', to='obywatele.Uzytkownik'),
        ),
        migrations.AddField(
            model_name='akceptacjaosoby',
            name='obywatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obywatel', to='obywatele.Uzytkownik'),
        ),
        migrations.AlterUniqueTogether(
            name='akceptacjaosoby',
            unique_together={('kandydat', 'obywatel')},
        ),
    ]
