# Generated by Django 3.0.7 on 2020-06-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputacja', models.SmallIntegerField(default=0, null=True)),
                ('polecajacy', models.CharField(editable=False, max_length=64, null=True)),
                ('data_przyjecia', models.DateField(editable=False, null=True)),
                ('uid', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AkceptacjaOsoby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydat', to='obywatele.Uzytkownik')),
                ('obywatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obywatel', to='obywatele.Uzytkownik')),
            ],
            options={
                'unique_together': {('kandydat', 'obywatel')},
            },
        ),
    ]
