# Generated by Django 3.1 on 2020-11-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0002_akceptacjaosoby_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='reputacja',
            new_name='reputation',
        ),
    ]
