# Generated by Django 3.1 on 2020-11-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0004_auto_20201108_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AkceptacjaOsoby',
            new_name='Rate',
        ),
    ]
