# Generated by Django 3.1 on 2020-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0005_auto_20201108_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='reputation',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
