# Generated by Django 3.1 on 2020-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0007_uzytkownik_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='bio',
            field=models.CharField(blank=True, editable=False, max_length=2000, null=True),
        ),
    ]
