# Generated by Django 3.1 on 2020-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0008_auto_20201125_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='bio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
