# Generated by Django 3.1 on 2020-12-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0010_auto_20201126_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='bio',
            new_name='to_give_away',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='fb_profil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='for_sale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='hobby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='i_know_personally_those_important_people',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='i_need',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='i_want_to_learn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='job',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='knowledge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='to_borrow',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
