# Generated by Django 3.1 on 2020-12-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0012_auto_20201224_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='fb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
