# Generated by Django 3.1 on 2020-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0013_uzytkownik_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
