# Generated by Django 3.1 on 2020-12-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0014_uzytkownik_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
