# Generated by Django 3.1 on 2020-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0015_uzytkownik_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='business',
            field=models.CharField(blank=True, help_text='If you are running a business', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='city',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='fb',
            field=models.CharField(blank=True, help_text='Link to Facebook profile', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='for_sale',
            field=models.CharField(blank=True, help_text='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='hobby',
            field=models.CharField(blank=True, help_text='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='i_need',
            field=models.CharField(blank=True, help_text='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='job',
            field=models.CharField(blank=True, help_text='Your profession', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='knowledge',
            field=models.CharField(blank=True, help_text='Knowledge you have', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.CharField(blank=True, help_text='Other things about worth mentioning', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, help_text='Tasks performed in our group', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='skills',
            field=models.CharField(blank=True, help_text='What practical skills do you have', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_borrow',
            field=models.CharField(blank=True, help_text='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_give_away',
            field=models.CharField(blank=True, help_text='Things you are willing to give away for free', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='want_to_learn',
            field=models.CharField(blank=True, help_text='Things you would like to learn', max_length=500, null=True),
        ),
    ]
