# Generated by Django 3.1 on 2020-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0018_auto_20201225_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, help_text='Tasks performed in our group', max_length=2000, null=True, verbose_name='Title'),
        ),
    ]
