# Generated by Django 3.1 on 2020-12-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0019_auto_20201225_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='business',
            field=models.CharField(blank=True, help_text='If you are running a business', max_length=200, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='city',
            field=models.CharField(blank=True, help_text='Where you are spending most of your time', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='fb',
            field=models.CharField(blank=True, help_text='Link to Facebook profile', max_length=500, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='for_sale',
            field=models.CharField(blank=True, help_text='Stuff you have for sale', max_length=500, null=True, verbose_name='For sale'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='hobby',
            field=models.CharField(blank=True, help_text='Hobbies you have', max_length=200, null=True, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='i_need',
            field=models.CharField(blank=True, help_text='What do you need', max_length=500, null=True, verbose_name='I need'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='job',
            field=models.CharField(blank=True, help_text='Your profession', max_length=500, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='knowledge',
            field=models.CharField(blank=True, help_text='Knowledge you have', max_length=500, null=True, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.CharField(blank=True, help_text='Other things about worth mentioning', max_length=500, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, help_text='Tasks performed in our group', max_length=2000, null=True, verbose_name='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='skills',
            field=models.CharField(blank=True, help_text='What practical skills do you have', max_length=500, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_borrow',
            field=models.CharField(blank=True, help_text='Stuff you can borrow to others', max_length=500, null=True, verbose_name='To borrow'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_give_away',
            field=models.CharField(blank=True, help_text='Things you are willing to give away for free', max_length=2000, null=True, verbose_name='To give away'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='want_to_learn',
            field=models.CharField(blank=True, help_text='Things you would like to learn', max_length=500, null=True, verbose_name='I want to learn'),
        ),
    ]
