# Generated by Django 3.1 on 2020-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0021_auto_20201225_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Tasks performed in our group', max_length=2000, null=True, verbose_name='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_give_away',
            field=models.TextField(blank=True, help_text='Things you are willing to give away for free', max_length=2000, null=True, verbose_name='To give away'),
        ),
    ]
