# Generated by Django 3.1 on 2020-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0022_auto_20201226_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='business',
            field=models.TextField(blank=True, help_text='If you are running a business', max_length=200, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='for_sale',
            field=models.TextField(blank=True, help_text='Stuff you have for sale', max_length=500, null=True, verbose_name='For sale'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='i_need',
            field=models.TextField(blank=True, help_text='What do you need', max_length=500, null=True, verbose_name='I need'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='knowledge',
            field=models.TextField(blank=True, help_text='Knowledge you have', max_length=500, null=True, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.TextField(blank=True, help_text='Other things about worth mentioning', max_length=500, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='skills',
            field=models.TextField(blank=True, help_text='What practical skills do you have', max_length=500, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_borrow',
            field=models.TextField(blank=True, help_text='Stuff you can borrow to others', max_length=500, null=True, verbose_name='To borrow'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='want_to_learn',
            field=models.TextField(blank=True, help_text='Things you would like to learn', max_length=500, null=True, verbose_name='I want to learn'),
        ),
    ]
