# Generated by Django 3.1 on 2020-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0023_auto_20201226_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='city',
            field=models.CharField(blank=True, help_text='Where one spend most of their time', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='hobby',
            field=models.CharField(blank=True, help_text='Hobbies one have', max_length=200, null=True, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='knowledge',
            field=models.TextField(blank=True, help_text='Knowledge one have', max_length=500, null=True, verbose_name='Knowledge'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.TextField(blank=True, help_text='Other things worth mentioning', max_length=500, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='skills',
            field=models.TextField(blank=True, help_text='Practical skills one have', max_length=500, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='to_give_away',
            field=models.TextField(blank=True, help_text='Things to are willing to give away for free', max_length=2000, null=True, verbose_name='To give away'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='want_to_learn',
            field=models.TextField(blank=True, help_text='Things one would like to learn', max_length=500, null=True, verbose_name='I want to learn'),
        ),
    ]
