# Generated by Django 3.1 on 2020-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0024_auto_20201226_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='business',
            field=models.TextField(blank=True, help_text='If running a business', max_length=200, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='fb',
            field=models.CharField(blank=True, help_text='Link to Facebook profile', max_length=500, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='job',
            field=models.CharField(blank=True, help_text='Profession', max_length=500, null=True, verbose_name='Job'),
        ),
    ]
