# Generated by Django 6.0.4 on 2026-07-02 23:47

from django.db import migrations, models


def combine_skills_knowledge_hobby(apps, schema_editor):
    Uzytkownik = apps.get_model('obywatele', 'Uzytkownik')

    for user in Uzytkownik.objects.all():
        parts = []
        if user.skills:
            parts.append(f"Umiejętności: {user.skills}")
        if user.knowledge:
            parts.append(f"Wiedza: {user.knowledge}")
        if user.hobby:
            parts.append(f"Hobby: {user.hobby}")

        if parts:
            user.skills_knowledge_hobby = " | ".join(parts)
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0025_populate_countries_and_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='skills_knowledge_hobby',
            field=models.CharField(blank=True, help_text='Skills, knowledge, and hobbies', max_length=1866, null=True, verbose_name='Skills / Knowledge / Hobby'),
        ),
        migrations.RunPython(combine_skills_knowledge_hobby),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='other',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='skills',
        ),
    ]
