# Generated by Django 3.1 on 2021-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0026_auto_20201227_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='gift',
            field=models.CharField(blank=True, help_text='What gift would you like to receive', max_length=500, null=True, verbose_name='Facebook'),
        ),
    ]
