# Generated by Django 3.1 on 2021-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0027_uzytkownik_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='gift',
            field=models.CharField(blank=True, help_text='What gift would you like to receive', max_length=500, null=True, verbose_name='Gift'),
        ),
    ]
