# Generated by Django 3.1.12 on 2021-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0029_auto_20210821_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='phone',
            field=models.TextField(blank=True, help_text='Phone number', max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
