# Generated by Django 6.0.4 on 2026-09-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0029_uzytkownik_event_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, help_text='Activities performed in our group', max_length=622, null=True, verbose_name='Responsibilities'),
        ),
    ]
