# Generated by Django 6.0.4 on 2026-09-02 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0030_alter_uzytkownik_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='email_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='daily', help_text='How often to receive email activity digests', max_length=10, verbose_name='Email frequency'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='last_email_digest_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last email digest sent at'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='push_notifications_post',
            field=models.BooleanField(default=True, help_text='Receive push notifications about new and updated documents', verbose_name='Push document notifications'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='push_notifications_survey',
            field=models.BooleanField(default=True, help_text='Receive push notifications about new surveys', verbose_name='Push survey notifications'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='push_notifications_task',
            field=models.BooleanField(default=True, help_text='Receive push notifications about new activities', verbose_name='Push activity notifications'),
        ),
    ]
