# Generated by Django 3.1.12 on 2021-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0030_uzytkownik_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
