# Generated by Django 6.0.4 on 2026-09-02 22:52

from django.db import migrations


def set_email_frequency_from_toggles(apps, schema_editor):
    """Set email_frequency to 'never' for users that had all old per-module toggles off."""
    Uzytkownik = apps.get_model('obywatele', 'Uzytkownik')
    for profile in Uzytkownik.objects.all():
        if not any(
            (
                profile.email_notifications_obywatele,
                profile.email_notifications_glosowania,
                profile.email_notifications_chat,
                profile.email_notifications_events,
            )
        ):
            profile.email_frequency = 'never'
            profile.save(update_fields=['email_frequency'])


def revert_email_frequency(apps, schema_editor):
    """No-op: the old toggles are not restored."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0031_uzytkownik_email_frequency_and_more'),
    ]

    operations = [
        migrations.RunPython(set_email_frequency_from_toggles, revert_email_frequency),
    ]
