# Generated by Django 3.1.12 on 2021-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0031_auto_20210911_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number i.e. +48 123 456 789', max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
