# Generated by Django 6.0.8 on 2026-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0032_auto_20260903_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='push_computer_enabled',
            field=models.BooleanField(default=True, help_text='Receive push notifications on desktop computers and laptops', verbose_name='Push on computer'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='push_phone_enabled',
            field=models.BooleanField(default=True, help_text='Receive push notifications on phones and tablets', verbose_name='Push on phone'),
        ),
    ]
