# Generated by Django 3.1.12 on 2021-09-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0033_uzytkownik_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='foto',
        ),
    ]
