# Generated by Django 6.0.8 on 2026-09-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0033_uzytkownik_push_computer_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='email_notifications_chat',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='email_notifications_events',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='email_notifications_glosowania',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='email_notifications_obywatele',
        ),
    ]
