# Generated by Django 5.2.16 on 2026-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0034_remove_uzytkownik_email_notifications_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='theme',
            field=models.CharField(choices=[('auto', 'Auto'), ('light', 'Bright'), ('dark', 'Dark')], default='auto', help_text='Preferred UI theme for web and emails', max_length=10, verbose_name='Theme'),
        ),
    ]
