# Generated by Django 3.1.12 on 2021-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0035_uzytkownik_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obywatele', verbose_name='Foto'),
        ),
    ]
