# Generated by Django 5.2.16 on 2026-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0035_uzytkownik_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='last_presence_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last activity'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='last_presence_source',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Activity source'),
        ),
    ]
