# Generated by Django 3.1.12 on 2021-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0036_auto_20210915_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='foto',
            field=models.ImageField(blank=True, default='anonymous.png', null=True, upload_to='obywatele', verbose_name='Foto'),
        ),
    ]
