# Generated by Django 6.0.8 on 2026-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0036_uzytkownik_last_presence_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrequest',
            name='publish_after_deletion',
            field=models.BooleanField(default=False, verbose_name='Publish feedback after deletion'),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='publish_anonymously',
            field=models.BooleanField(default=True, verbose_name='Publish feedback anonymously'),
        ),
    ]
