# Generated by Django 3.1.12 on 2021-09-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0037_auto_20210917_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='foto',
            field=models.ImageField(blank=True, default='obywatele/anonymous.png', null=True, upload_to='obywatele', verbose_name='Foto'),
        ),
    ]
