# Generated by Django 6.0.8 on 2026-09-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0037_deletionrequest_publish_after_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='contact_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Contact profile link'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='phone_country',
            field=models.CharField(blank=True, default='PL', max_length=2, verbose_name='Phone country'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Telephone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('signal', 'Signal')], default='', max_length=16, verbose_name='Preferred contact method'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number in international format', max_length=32, null=True, verbose_name='Phone number'),
        ),
    ]
