# Generated by Django 6.0.8 on 2026-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0038_uzytkownik_contact_link_uzytkownik_phone_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a local or international phone number', max_length=32, null=True, verbose_name='Phone number'),
        ),
    ]
