# Generated by Django 6.0.8 on 2026-09-14 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0039_alter_uzytkownik_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='muted_push_users',
            field=models.ManyToManyField(blank=True, related_name='push_muted_by', to=settings.AUTH_USER_MODEL, verbose_name='Muted people'),
        ),
    ]
