# Generated by Django 6.0.8 on 2026-09-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0040_uzytkownik_muted_push_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Private note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes_authored', to='obywatele.uzytkownik', verbose_name='Author')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes_received', to='obywatele.uzytkownik', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Private note',
                'verbose_name_plural': 'Private notes',
                'constraints': [models.UniqueConstraint(fields=('author', 'subject'), name='unique_private_note_author_subject')],
            },
        ),
    ]
