# Generated by Django 3.1.12 on 2021-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0041_auto_20210930_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='hobby',
            field=models.TextField(blank=True, help_text='Hobbies one have', max_length=2000, null=True, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Tasks performed in our group', max_length=600, null=True, verbose_name='Responsibilities'),
        ),
    ]
