# Generated by Django 6.0.8 on 2026-09-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0041_privatenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='responsibilities',
        ),
    ]
