# Generated by Django 6.0.8 on 2026-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0042_remove_uzytkownik_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='business_active',
            field=models.BooleanField(default=False, verbose_name='I run my own business'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='business_description',
            field=models.TextField(blank=True, default='', max_length=1866, verbose_name='What does your business do?'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='business_website',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Business website'),
        ),
    ]
