# Generated by Django 3.1.12 on 2021-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0042_auto_20210930_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Tasks performed in our group', max_length=622, null=True, verbose_name='Responsibilities'),
        ),
    ]
