# Generated by Django 6.0.8 on 2026-09-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0044_migrate_business_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='business',
        ),
    ]
