# Generated by Django 3.1.12 on 2021-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0044_auto_20210930_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='fb',
            field=models.CharField(blank=True, help_text='Link to Facebook profile', max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='gift',
            field=models.CharField(blank=True, help_text='What gift would you like to receive', max_length=73, null=True, verbose_name='Gift'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='job',
            field=models.CharField(blank=True, help_text='Profession', max_length=72, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.CharField(blank=True, help_text='Other things worth mentioning', max_length=74, null=True, verbose_name='Other'),
        ),
    ]
