# Generated by Django 6.0.8 on 2026-09-26 21:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0045_remove_uzytkownik_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', max_length=1866, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resource_items', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('give', 'Give away'), ('borrow', 'Lend'), ('sale', 'For sale'), ('need', 'I need')], max_length=10, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='obywatele.uzytkownik', verbose_name='Profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='obywatele.resourceitem', verbose_name='Resource')),
            ],
            options={
                'ordering': ('kind', 'item__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='resourceitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_resource_item_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('profile', 'item', 'kind'), name='unique_resource_assignment'),
        ),
    ]
