# Generated by Django 3.1.12 on 2021-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0045_auto_20210930_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='fb',
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='business',
            field=models.CharField(blank=True, help_text='If running a business', max_length=72, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='city',
            field=models.CharField(blank=True, help_text='Where one spend most of their time', max_length=72, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='gift',
            field=models.CharField(blank=True, help_text='What gift would you like to receive', max_length=72, null=True, verbose_name='Gift'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='other',
            field=models.CharField(blank=True, help_text='Other things worth mentioning', max_length=1000, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number i.e. +48 123 456 789', max_length=72, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='responsibilities',
            field=models.CharField(blank=True, help_text='Tasks performed in our group', max_length=72, null=True, verbose_name='Responsibilities'),
        ),
    ]
