# Generated by Django 6.0.8 on 2026-09-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0047_migrate_legacy_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='i_need',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='to_borrow',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='to_give_away',
        ),
    ]
