# Generated by Django 6.0.8 on 2026-09-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0048_remove_uzytkownik_for_sale_remove_uzytkownik_i_need_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='description',
        ),
    ]
