# Generated by Django 6.0.8 on 2026-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0049_remove_resourceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='push_notifications_glosowania',
            field=models.BooleanField(default=False, help_text='Receive push notifications about law proposals and voting', verbose_name='Push voting notifications'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='push_notifications_obywatele',
            field=models.BooleanField(default=False, help_text='Receive push notifications about new citizens and membership requests', verbose_name='Push citizenship notifications'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='push_notifications_post',
            field=models.BooleanField(default=False, help_text='Receive push notifications about new and updated documents', verbose_name='Push document notifications'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='push_notifications_survey',
            field=models.BooleanField(default=False, help_text='Receive push notifications about new surveys', verbose_name='Push survey notifications'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='push_notifications_task',
            field=models.BooleanField(default=False, help_text='Receive push notifications about new activities', verbose_name='Push activity notifications'),
        ),
    ]
