# Generated by Django 6.0.8 on 2026-09-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0050_alter_uzytkownik_push_notifications_glosowania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='notifications_unsubscribe_source',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Unsubscribe source'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='notifications_unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='All notifications unsubscribed at'),
        ),
    ]
