# Generated by Django 3.1.13 on 2021-11-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obywatele', '0050_auto_20211121_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='uid',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
