# Generated by Django 6.0.8 on 2026-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0051_uzytkownik_notifications_unsubscribe_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenactivity',
            name='activity_type',
            field=models.CharField(choices=[('new_candidate', 'New Candidate'), ('user_activated', 'User Activated'), ('user_blocked', 'User Blocked'), ('deletion_requested', 'Account deletion requested')], max_length=20),
        ),
    ]
