# Generated by Django 6.0.8 on 2026-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('obywatele', '0052_alter_citizenactivity_activity_type')]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='push_notifications_bookkeeping',
            field=models.BooleanField(default=False, help_text='Receive push notifications about new financial transactions', verbose_name='Push finance notifications'),
        )
    ]
