# Generated by Django 6.0.8 on 2026-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0053_uzytkownik_push_notifications_bookkeeping'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1866, verbose_name='Description'),
        ),
    ]
