# Generated by Django 6.0.8 on 2026-10-03 20:57

import django.db.models.functions.text
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def copy_resource_item_fields(apps, schema_editor):
    ResourceAssignment = apps.get_model('obywatele', 'ResourceAssignment')
    db_alias = schema_editor.connection.alias
    assignments = ResourceAssignment.objects.using(db_alias).select_related('item')
    for assignment in assignments.iterator():
        assignment.name = assignment.item.name
        assignment.description = assignment.item.description
        assignment.save(using=db_alias, update_fields=['name', 'description'])


def prevent_reverse_resource_split(apps, schema_editor):
    raise IrreversibleError('Individual resources cannot be merged back into the shared catalogue safely.')


class Migration(migrations.Migration):
    dependencies = [('obywatele', '0054_resourceitem_description')]

    operations = [
        migrations.RemoveConstraint(model_name='resourceitem', name='unique_resource_item_name_ci'),
        migrations.AlterModelOptions(name='resourceassignment', options={'ordering': ('kind', 'name')}),
        migrations.RemoveConstraint(model_name='resourceassignment', name='unique_resource_assignment'),
        migrations.AddField(model_name='resourceassignment', name='description', field=models.TextField(blank=True, default='', max_length=1866, verbose_name='Description')),
        migrations.AddField(model_name='resourceassignment', name='name', field=models.CharField(max_length=200, null=True, verbose_name='Name')),
        migrations.RunPython(copy_resource_item_fields, migrations.RunPython.noop),
        migrations.AlterField(model_name='resourceassignment', name='name', field=models.CharField(max_length=200, verbose_name='Name')),
        migrations.AddConstraint(
            model_name='resourceassignment', constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('profile'), models.F('kind'), name='unique_resource_assignment_name_ci')
        ),
        migrations.RemoveField(model_name='resourceassignment', name='item'),
        migrations.DeleteModel(name='ResourceItem'),
        migrations.RunPython(migrations.RunPython.noop, prevent_reverse_resource_split),
    ]
