# Generated by Django 3.1.12 on 2021-08-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
