# Generated by Django 3.1.12 on 2021-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_auto_20210915_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
