# Generated by Django 3.1.12 on 2021-09-17 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0003_ebook_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='file3',
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_epub',
            field=models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['epub'])], verbose_name='epub'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['mobi'])], verbose_name='mobi'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(blank=True, default='elibrary/default.png', null=True, upload_to='elibrary', verbose_name='Cover'),
        ),
    ]
