# Generated by Django 3.1.12 on 2021-09-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0004_auto_20210917_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebook',
            options={'ordering': ('id',), 'verbose_name_plural': 'eBooks'},
        ),
        migrations.AddField(
            model_name='ebook',
            name='genre',
            field=models.CharField(choices=[('sf', 'SF'), ('społdzielczość', 'SPÓŁDZIELCZOŚĆ'), ('historia', 'HISTORIA')], default='sf', max_length=100),
        ),
    ]
