# Generated by Django 3.1.12 on 2021-09-18 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elibrary', '0006_auto_20210918_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ebook',
            new_name='Book',
        ),
    ]
