# Generated by Django 3.1.12 on 2021-09-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0007_auto_20210918_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='elibrary/default.png', help_text='Picture proportions should 2/3. I.e. width x 1.5 = height', null=True, upload_to='elibrary', verbose_name='Cover'),
        ),
    ]
