# Generated by Django 3.1.12 on 2021-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0010_auto_20210918_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
    ]
