# Generated by Django 3.1.12 on 2021-09-18 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0011_remove_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_mobi',
            field=models.FileField(blank=True, default=None, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['mobi'])], verbose_name='mobi'),
        ),
    ]
