# Generated by Django 3.1.12 on 2021-09-18 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0012_auto_20210918_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='elibrary/default.png', help_text='Cover proportions should be 2/3. I.E. width x 1.5 = height', null=True, upload_to='elibrary', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['mobi'])], verbose_name='mobi'),
        ),
    ]
