# Generated by Django 6.0.4 on 2026-09-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_post_slug'),
        ('chat', '0022_room_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='chat.room', verbose_name='Chat room'),
        ),
    ]
