# Generated by Django 5.2.16 on 2026-09-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_backfill_post_chat_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
