# Generated by Django 6.0.8 on 2026-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_convert_private_posts_to_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('group', 'Group'), ('public', 'Public'), ('archive', 'Archive')], default='group', max_length=10, verbose_name='Visibility'),
        ),
    ]
